# DO NOT EDIT THIS FILE
from http.server import BaseHTTPRequestHandler
import random
import os

class Handler(BaseHTTPRequestHandler):

    def _send_cors_headers(self):
        """Sends the CORS headers."""
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type')

    def do_OPTIONS(self):
        """Handles preflight CORS requests."""
        self.send_response(204) # No Content
        self._send_cors_headers()
        self.end_headers()

    def do_GET(self):
        try:
            # Get the directory of the current script to build an absolute path to the data file.
            # This is the most reliable way to locate the file in a serverless environment.
            script_dir = os.path.dirname(__file__)
            file_path = os.path.join(script_dir, 'jokes.txt')

            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()

            # Split jokes by newline and filter out any empty or whitespace-only lines
            jokes = [joke for joke in content.splitlines() if joke.strip()]

            if not jokes:
                self.send_response(500)
                self.send_header('Content-type', 'text/plain')
                self._send_cors_headers()
                self.end_headers()
                self.wfile.write(b"No jokes found in the file.")
                return

            # Choose a random joke from the list
            random_joke = random.choice(jokes)

            # Send a successful (200 OK) response
            self.send_response(200)
            self.send_header('Content-type', 'text/plain; charset=utf-8')
            self._send_cors_headers()
            self.end_headers()
            self.wfile.write(random_joke.encode('utf-8'))

        except FileNotFoundError:
            self.send_response(500)
            self.send_header('Content-type', 'text/plain')
            self._send_cors_headers()
            self.end_headers()
            error_message = f"Error: 'jokes.txt' not found. Make sure it's in the 'api/dadjoke' directory.".encode('utf-8')
            self.wfile.write(error_message)
        except Exception as e:
            self.send_response(500)
            self.send_header('Content-type', 'text/plain')
            self._send_cors_headers()
            self.end_headers()
            self.wfile.write(f"An internal server error occurred: {e}".encode('utf-8'))

        return
