# .github/workflows/build.yml
# This GitHub Actions workflow verifies that the project can be successfully built by Vercel.
# It runs on every pull request that targets the 'master' branch to catch build errors early.

name: "Verify Vercel Build"

on:
  pull_request:
    branches:
      - master
  # Optional: also run on pushes to master to ensure the main branch is always healthy
  push:
    branches:
      - master

jobs:
  verify-build:
    name: "Verify Build with Vercel CLI"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Set up Node.js environment"
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Use a specific Node.js version compatible with Vercel

      - name: "Cache npm packages"
        uses: actions/cache@v4 # Use caching to speed up Vercel CLI installation
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: "Install Vercel CLI"
        run: npm install --global vercel

      - name: "Pull Vercel Project Settings"
        # This step uses `vercel pull` to generate the required .vercel/project.json file.
        # We provide a dummy token because the command requires authentication, but for a simple
        # build verification, we don't need access to a real Vercel project.
        # This is more reliable than creating the file manually.
        run: vercel pull --yes --environment=preview

      - name: "Run Vercel Build Command"
        # This command simulates a production build. It will install dependencies
        # for all serverless functions (Go, Python, etc.) and attempt to build them.
        # The job will fail if there are any build errors.
        run: vercel build
